name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24, 25, 26, 27]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: rebar3 compile
      - name: Run dialyzer
        run: rebar3 dialyzer
      - name: Run tests
        run: rebar3 as test eunit
